### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by mckayfackrell** [WebDevSimplified/chat-gpt-api#1]
Not sure if you really wanted to commit your .env file. Looks like your API key is in there.

**Comment by maximiliansteiger** [comment]
Key is not valid anymore.

**Comment by Vijaykv5** [comment]
@maximiliansteiger How to fix that I got the same issue

**Comment by mckayfackrell** [comment]
> @maximiliansteiger How to fix that I got the same issue

You need to create your own API key

**Comment by Vijaykv5** [comment]
> > @maximiliansteiger How to fix that I got the same issue
> 
> You need to create your own API key

But if I made integrated in a website , will it work for every one interacting with my website

**Comment by mckayfackrell** [comment]
> > > @maximiliansteiger How to fix that I got the same issue
> 
> > 
> 
> > You need to create your own API key
> 
> 
> 
> But if I made integrated in a website , will it work for every one interacting with my website
> 
> 

Yes it will, however, most API's have a limit. For (x) amount of requests made, the service will either stop/slow down/or start charging money.

**Comment by WebDevSimplified** [comment]
You are correct. Sorry it took so long to see this. I already have updated the code to remove the env file.
