### ISSUE TITLE
api key is public

### ISSUE THREAD

**Issue by sohaibMan** [WebDevSimplified/chat-gpt-api#2]

**Comment by maximiliansteiger** [comment]
Key is not valid anymore.

**Comment by sohaibMan** [comment]
Even the key is not valid , it should not be Revaled

**Comment by theisoj** [comment]
I made a pull request for the .gitignore file to be added to the repository.

**Comment by WebDevSimplified** [comment]
You are correct. Sorry it took so long to see this. I already have updated the code to remove the env file.
